Remove artifactory image pushing momentarily

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -179,29 +179,29 @@ default:
   script:
     - gunzip -c image.tar.gz | docker load
     # Push to Artifactory with the same tag as built in the 1-build-image job
-    - |
-      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
-        export IMAGE_TAG="$(echo ${ENVIRONMENT:-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | tr '/' '-')"
-      elif [ "$CI_COMMIT_TAG" ]; then
-        export IMAGE_TAG="$CI_COMMIT_TAG"
-      else
-        export IMAGE_TAG="$CI_DEFAULT_BRANCH"
-      fi
-    - echo "Pushing image sd-submit-api:${IMAGE_TAG}"
-    - |
-      max_retries=150
-      retry=1
+    # - |
+    #   if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
+    #     export IMAGE_TAG="$(echo ${ENVIRONMENT:-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | tr '/' '-')"
+    #   elif [ "$CI_COMMIT_TAG" ]; then
+    #     export IMAGE_TAG="$CI_COMMIT_TAG"
+    #   else
+    #     export IMAGE_TAG="$CI_DEFAULT_BRANCH"
+    #   fi
+    # - echo "Pushing image sd-submit-api:${IMAGE_TAG}"
+    # - |
+    #   max_retries=150
+    #   retry=1
 
-      until docker push "$ARTIFACTORY_SERVER/sds/sd-submit-api:${IMAGE_TAG}" ; do
-        if [ "$retry" -ge "$max_retries" ]; then
-           echo "docker push failed after $max_retries attempts"
-           exit 1
-        fi
+    #   until docker push "$ARTIFACTORY_SERVER/sds/sd-submit-api:${IMAGE_TAG}" ; do
+    #     if [ "$retry" -ge "$max_retries" ]; then
+    #        echo "docker push failed after $max_retries attempts"
+    #        exit 1
+    #     fi
 
-        echo "Attempt $retry failed, retrying in 10 seconds..."
-        retry=$((retry + 1))
-        sleep 10
-      done
+    #     echo "Attempt $retry failed, retrying in 10 seconds..."
+    #     retry=$((retry + 1))
+    #     sleep 10
+    #   done
     - |
       # We want to only push images to github on release.
       if [ -n "$CI_COMMIT_TAG" ]; then
